name: Deploy to Github Pages
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'jerrylususu'
        reponame: 'gojuon-quiz'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        useyarn: true
        gitmsg: "Deploy gojuon quiz"
